### ISSUE TITLE
Impact of renaming CDBS

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsynphot_refactor#114]
RedCat has plans to rename CDBS (possibly to TRDS, see https://jira.stsci.edu/browse/REDCAT-111).

**Affected code**

* Documentation:
    - [x] Example paths need to be updated. See #121 
    - [x] Instructions on where to download data need to be updated. See #121
* Code:
    - [x] ~**Breaking change:** Can we keep `PYSYN_CDBS` environment variable name or it needs to change too?~ No change.
    - [x] Defaults in `config` need to be updated. This also means that server needs updating. See #121 
    - [x] Test(s) pointing to old server path needs to be updated. This change is not user-facing. See #121 
* Legacy materials (we will **not** update these):
    * Everything in `legacy_materials`.

**Action items**

- [x] Make changes to package as documented above. See #121 
- [x] Make a software release with bump to major version.
- [x] ~Add a note/warning to package front page about this change.~ There is very little user-facing change, so not needed.
- [x] ~Add a pinned issue about this change.~ There is very little user-facing change, so not needed.

cc @rizeladiaz and @vglaidler 

xref spacetelescope/pysynphot#131 and spacetelescope/synphot_refactor#270 

p.s. Will revisit the need to add a note/warning and/or pinned issue in the future if there are a lot of confused users.
